config/routes.rb
Lectito::Application.routes.draw do

  match '/'=> "splash#index"
  match '/subscribe'=> "splash#subscribe"

  match '/auth/:service/callback' => 'sessions#create'
  match '/logout' => 'sessions#destroy'
  match '/login' => 'sessions#new'

  resources :users do
    resources :collections
    resources :links
    member do
      get :frequently, :friends, :followers, :following
      post :block, :unblock, :follow, :unfollow
    end
    resources :authorizations
  end
  resources :collections do
    resources :memberships
  end

  resources :stories, :shelves,:editions
    
  resources :books do
    member do
      post :shelf
      post :collection
      post :tag
      post :lend
      post :return
    end
    collection do
      get :count
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :authorizations
  has_many :shelves,:order=>"name"
  has_many :collections
  has_many :books, :through => :collections
  has_many :borrowed_books, :class_name=>"Book", :foreign_key=>:borrower_id
  has_many :tags

  has_many :links

  has_one :public_collection, :class_name=>"Collection", 
  :conditions=>{public: true}
  has_one :private_collection, :class_name=>"Collection", 
  :conditions=>{public: true}

  has_many :following_rel, :foreign_key=>"follower_id",
  :class_name => "Relationship",:dependent=>:destroy
  has_many :follower_rel, :foreign_key=>"followed_id",
  :class_name => "Relationship",:dependent=>:destroy
  has_many :following, :through => :following_rel, :source => :followed
  has_many :followers, :through => :follower_rel, :source => :follower

  def initialize(*args)
    # AR finder methods call #allocate not #new so this *shouldn't* 
    # be called on objects that are retrieved from DB, only on 
    # genuinely new ones.  But we will check anyway
    super
    if self.new_record? then
      self.public_collection||=Collection.new(public: true, 
                                              name: 'Public books')
      self.private_collection||=Collection.new(private: true,
                                               name: 'Private books')
    end
  end

  def friends
    (self.collections.map(&:users).flatten +
     self.following + self.followers ).uniq
  end

  def name
    "#{nickname} (#{fullname})"
  end

  def welcome!
    Event.publish(:actor=>self,:action=>:join)
  end
  
  def events
    Event.where("actor_id=? or recipient_id=?",self.id,self.id).order("created_at desc")
  end

  def stories(limit=20,offset=0)
    story=Story.new
    Enumerator.new do |y|
      self.events.order('created_at desc').as_batches do |e|
        if story.accepts_event? e then
          story.created_at ||= e.created_at
          story.add_event e
        else
          if offset.zero?
            y << story
            limit-=1
          else
            offset-=1
          end
          break if limit.zero?
          story=Story.new
          story.add_event e
          story.created_at=e.created_at
        end
      end
      y << story
    end
  end


  def all_books
    books + borrowed_books
  end

  def tagnames
    Tagname.all(self)
  end

  def admin?
    false
  end

  def blocking?(user)
    r=Relationship.unscoped.where(removed_at: nil, follower_id: user.id,
                                  followed_id: self.id).first
    r and r.blocked_at 
  end

  def following?(user)
    r=Relationship.find_by_follower_id_and_followed_id(self.id,user.id) 
    r and !r.blocked_at
  end

  def follow(user)
    if user.blocking?(self) || self.blocking?(user) then
      raise "Blocked"
    else
      # once a user has been followed and unfollowed, a *new* relationship
      # is created if they are subsequently followed again.  Just because we 
      # think it would be useful to have the history in case of complaints
      Relationship.
        find_or_create_by_follower_id_and_followed_id(self.id,user.id)
    end
  end

  def unfollow(user)
    r=Relationship.find_by_follower_id_and_followed_id(self.id,user.id)
    r.unfollow
  end

  def block(user)
    r=Relationship.unscoped.where(removed_at: nil).find_or_create_by_follower_id_and_followed_id(user.id,self.id)
    unless r.blocked_at
      r.blocked_at=Time.now
      r.save
    end
  end

  def unblock(user)
    r=Relationship.unscoped.where(removed_at: nil).find_by_follower_id_and_followed_id(user.id,self.id)
    r and r.unblock
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    respond_with  @user=User.new
  end
  def index
    respond_with @users=current_user.friends
  end
  def friends
    u=current_user.friends
    from=params[:from].to_i 
    to=params[:to].to_i 
    u=
      if t=params[:term] then
        u.find_all {|u| u.name.match Regexp.new(t,Regexp::IGNORECASE) }
      else
        u
      end
    # upper bound is exclusive not inclusive
    to=if to.zero? then to.count else to-1 end
    respond_with @users=u[from..to]
  end

  def frequently
    @user=UserDecorator.find(params[:id])
    @users=UserDecorator.decorate(User.limit(10))
    respond_with @users
  end

  def followers
    @user=UserDecorator.find(params[:id])
    @breadcrumbs=[["friends",following_user_path(@user)]]
    @followers=@user.followers
  end

  def following
    @user=UserDecorator.find(params[:id])
    @breadcrumbs=[["friends",following_user_path(@user)]]
    @following=@user.following
  end

  def edit
    @user=UserDecorator.find(params[:id])
    @authorizations=@user.authorizations
  end

  def update
    @user=User.find(params[:id])
    if @user==current_user
      if auth=params[:authorizations]
        @user.authorizations= Authorization.find(auth.keys.map(&:to_i))
      end
      
      @user.update_attributes params[:user]
      redirect_to action: :edit
    else
      render text: "Forbidden", status: :forbidden
    end
  end

  def show
    @user=UserDecorator.find(params[:id])
    # placeholder stories collection so we can fiddle with layout
    @stories= StoryDecorator.decorate(User.find(1).stories(0,10).to_a)
    respond_with @user
  end
  
  def block
    current_user.block(@user=UserDecorator.find(params[:id]))
    redirect_to action: :show
  end

  def unblock
    current_user.unblock(@user=UserDecorator.find(params[:id]))
    redirect_to action: :show
  end

  def follow
    current_user.follow(@user=UserDecorator.find(params[:id]))
    redirect_to action: :show
  end

  def block
    current_user.block(@user=UserDecorator.find(params[:id]))
    redirect_to action: :show
  end

  def unblock
    current_user.unblock(@user=UserDecorator.find(params[:id]))
    redirect_to action: :show
  end

  def unfollow
    current_user.unfollow(@user=UserDecorator.find(params[:id]))
    redirect_to action: :show
  end

  def breadcrumb
    @breadcrumbs=[["profile",current_user]]
  end
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
<% if @user.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@link.errors.count, "error") %> stopped us from saving this:</h2>
  
  <ul>
    <% @link.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="field">
  <%= f.label :nickname %>
  <%= f.text_field :nickname %>
</div>
<div class="field">
  <%= f.label :fullname %>
  <%= f.text_field :fullname %>
</div>
<div class="field">
  <%= f.label :email %>
  <%= f.text_field :email %>
</div>
<div class="field">
  <%= f.label :bio %>
  <%= f.text_area :bio, rows: 5, cols: 40 %>
</div>
<% @user.links.each_with_index do |l,i| %>
<div class="field">
  <%= f.label(i.zero? ? :links : ' '.to_sym )  %>
  <span class=link><%= l.title %> </span>
  <span class=link><%= l.url %> </span>
  <span><%= link_to "[ edit ]", edit_user_link_path(@user,l) %></span>
  <span><%= link_to "[ delete ]", {action: :destroy, id: l.id},{method: :delete} %></span>
</div>
<% end %>
<div class="field">
  <%= f.label "New link" %>
  <%= link_to "Add", new_user_link_path(@user) %>
</div>


<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/users/_friend_class_leftbar.html.erb
<% sel=lambda {|x| (x==section) ? 'class=selected' : '' } %>
<div id="friend_class_leftbar">
<ul class=classes>
  <li <%= sel.('profile') %> >
    <%= link_to "Profile", @user  %> </li>
  <li <%= sel.('links') %> >
    <%= link_to "Links", user_links_path(@user)  %> </li>
  <li <%= sel.('following') %> >
    <%= link_to "Following", following_user_path(@user)  %> </li>
  <li <%= sel.('followers') %> >
    <%= link_to "Followers", followers_user_path(@user)  %> </li>
<% if @user==current_user %>
  <li <%= sel.('groups') %> >
    <%= link_to "Groups ", user_collections_path(@user) %>
    <ul class=groups>
      <% @user.collections.each do |c| %>
      <li> <%= link_to c.name,collection_memberships_path(c) %> </li>
      <% end %>
    </ul>
  </li>
  <li <%= sel.('authorizations') %> >
    <%= link_to "Linked accounts", user_authorizations_path(@user)  %> </li>
<% end %>
</ul>
</div>

app/views/users/_profile_header.html.erb
<h1>
  <div class=nickname><%= @user.nickname %></div>
  <div class=fullname><%= @user.fullname %></div>
</h1>

<div id=profile_rightbar>
<%= image_tag @user.avatar_or_blank  %>
<%= @user.bio %>
<ul>
<% @user.links.each do |l| %>
<li> <%= link_to l.title,l.url %>
<% end %>
</li>
</ul>
</div>

<%= actions_bar(@user.actions) %>

<% sel=lambda {|x| (x==section) ? 'class=selected' : '' } %>
<div id="profile_leftbar">
<ul class=classes>
  <li <%= sel.('news') %> >
    <%= link_to "News", @user  %> </li>
  <li <%= sel.('following') %> >
    <%= link_to "Following", following_user_path(@user)  %> </li>
  <li <%= sel.('followers') %> >
    <%= link_to "Followers", followers_user_path(@user)  %> </li>
<% if @user==current_user %>
  <li <%= sel.('groups') %> >
    <%= link_to "Groups ", user_collections_path(@user) %>
    <ul class=groups>
      <% @user.collections.each do |c| %>
      <li> <%= link_to c.name,collection_memberships_path(c) %> </li>
      <% end %>
    </ul>
  </li>
  <li <%= sel.('authorizations') %> >
    <%= link_to "Linked accounts", user_authorizations_path(@user)  %> </li>
<% end %>
</ul>
</div>

app/views/users/_row.html.erb
<div class=row>
  <span class=avatar> <%= row.avatar and image_tag(row.avatar) %> </span>
  <span class=name>
    <span class=nick><%= row.nickname %></span><br>
    <span class=full><%= row.fullname %> </span>
  </span>
  <span class=actions>
    <%= actions_dropdown row.actions %>
  </span>
</div>

app/views/users/edit.html.erb
<%= render partial: 'users/profile_header', locals: {section: 'edit'} %>
<div class=profile_body>
  <h2>Edit profile</h2>
  <%= render 'form' %>
</div>

app/views/users/followers.html.erb
<%= render partial: 'profile_header', locals: {section: 'followers'} %>
<div class=profile_body>

<%= render :partial=>"row", :collection=> @followers or
  "This user has no followers (yet?)"
%>
</div>

app/views/users/following.html.erb
<%= render partial: 'profile_header', locals: {section: 'following'} %>
<div class=profile_body>
<%= render :partial=>"row", :collection=> @following or
  "This user is not following anyone"
%>
</div>

app/views/users/frequently.html.erb
<div class=friends_list>
<input name='find' size=60 placeholder='find a user' />
<br clear=both>
<% @users.each do |u| %>
<div class=user>
  <a href="<%= url_for u %>">
    <img 
       src="<%= u.avatar ? u.avatar : "/question-mark-face.jpg" %>"
       />
    <span class=caption><%= u.fullname %></span>
  </a>
</div>
<% end %>
</div>

app/views/users/show.html.erb
<%= render partial: 'profile_header', locals: {section: 'news'} %>

<div class=profile_body>
stories go here




</div>