config/routes.rb
Lectito::Application.routes.draw do

  match '/'=> "splash#index"
  match '/subscribe'=> "splash#subscribe"

  match '/auth/:service/callback' => 'sessions#create'
  match '/logout' => 'sessions#destroy'
  match '/login' => 'sessions#new'

  resources :users do
    resources :collections
    resources :links
    member do
      get :frequently, :friends, :followers, :following
      post :block, :unblock, :follow, :unfollow
    end
    resources :authorizations
  end
  resources :collections do
    resources :memberships
  end

  resources :stories, :shelves,:editions
    
  resources :books do
    member do
      post :shelf
      post :collection
      post :tag
      post :lend
      post :return
    end
    collection do
      get :count
    end
  end

end

app/models/story.rb
class Story 
  def self.for_events events
    story=nil
    s=[]
    if events then
      events.each do |e|
        if story && story.accepts_event?(e) then
          story.add_event e
        else
          if story then 
            s << story
          end
          story=Story.new
          story.add_event e
          story.created_at=e.created_at
        end
      end
      s << story
    end
    s
  end

  attr_accessor :events,:created_at

  def image
    nil
  end

  def initialize(*args)
    @events||=[]
    super
  end
  
  def books 
    @events.map(&:book).uniq
  end
  
  [:action,:actor,:recipient].each do |m|
    define_method m do
      @events[0].send(m)
    end
  end

  def add_event e
    @events << e
  end
  def accepts_event? ev
    if @events.empty? then true
    else
      e=@events[0]
      [:actor_id,:action,:recipient_id].map {|k| e.send(k)==ev.send(k)}.all?
    end
  end
  def to_partial_path
    self.action.to_s
  end

  def book_names_truncated
    c=self.books.count
    examples=self.books[0..3]
    if c<=examples.count then
      examples.map {|b| "#{b.title} by #{b.author}" }.to_sentence
    else
      names=examples.map {|b| "#{b.title} by #{b.author}"  }.join(", ")
      "#{names} and #{c-examples.count} other books"
    end
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def index
    page_size=20
    @page=(params[:page] || 1).to_i 
    # ask for one more than we need, so we know if there's a page following 
    # this one
    @stories=StoryDecorator.decorate(current_user.stories(1+page_size,(@page-1)*page_size).to_a)
    @next=(@stories.length > page_size) && params.merge(:page=>@page+1)
    @prev=(@page>1) &&  params.merge(:page=>@page-1)
    @stories.pop
  end
  def breadcrumb
    @breadcrumbs=[["news",stories_path]]
  end
end

app/views/stories/_follow.html.erb
<div class="story">
  <div class=dateline><%= l(story.created_at) %></div>
<%= link_to story.actor.name_or_subject_pronoun,story.actor %> is now following
<%= link_to story.recipient.name_or_object_pronoun,story.recipient %> 
<br clear=both>
</div>

app/views/stories/_join.html.erb
<div class="story">
  <div class=dateline><%= l(story.created_at) %></div>
Welcome <%= story.actor.name %> to the  booksh.lv community!  Now you
can 
<%= link_to "set up your profile",story.actor %>, 
<%= link_to "start adding your books and collections",Book %>,  
<%= link_to "browse books", editions_path %> that other members have 
added, and look for your
<%= link_to "friends.", following_user_path(story.actor) %> 
<br clear=both>
</div>

app/views/stories/_lend.html.erb
<% books=BookDecorator.decorate(story.books).to_ary %>
<div class="story">
  <div class=dateline><%= l(story.created_at) %></div>
<%= link_to story.actor.name_or_subject_pronoun(:capitalize),story.actor%> 
lent
<%= link_to books[0].title_and_author, books[0] %>
to
<%= link_to story.recipient.name,story.recipient %> 
</div>

app/views/stories/_new.html.erb
<div class="story">
  <div class=dateline><%= l(story.created_at) %></div>
<%= story.actor.name %> added <%= story.book_names_truncated %>
to their library
<br clear=both>
</div>

app/views/stories/index.html.erb
<h1>Recently</h1>
<%= render :partial => @stories, as: :story %>
<div class=pagination>
<% if @next then %>
<%= link_to "Older >", @next %>
<% end  %>
<% if @prev then %>
<%= link_to "< Newer", @prev %>
<% end  %>
</div>